### ISSUE TITLE
Fix USB trouble

### ISSUE THREAD

**Issue by docpillman** [RoboticsHardwareSolutions/BareMetal-PLC-M#1]
<sub><a href="https://huly.app/guest/roboticshardwaresolutions?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzMxMTQ2YmU3Y2M1YTc4NTQyYTZhZDgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZG9jcGlsbG1hbi1yb2JvdGljc2hhcmQtNjczMTExMzEtZDM2ODkzZGQ3My1hOWYyMjgifQ.JMa7Vx_oNXp1LsdxTF_AFlAFnMMmGsLjezyz5r1AbNQ">Huly&reg;: <b>BAREM-1</b></a></sub>

**Comment by lKanifoll** [comment]
Есть чатик по теме

**Comment by docpillman** [comment]
Ага

**Comment by docpillman** [comment]
Оч прикольно

**Comment by docpillman** [comment]
Есть еще интергация с TG

**Comment by docpillman** [comment]
Ток чет не заводится

**Comment by lKanifoll** [comment]
да, просто повисело и пропало

**Comment by docpillman** [comment]
Зато в почту исправно спамит )

**Comment by lKanifoll** [comment]
Вот это ваще лишнее

**Comment by docpillman** [comment]
Интересно если разворачивать у себя чатик тоже зависит от LiveKit или только видео и аудио от него зависит

**Comment by lKanifoll** [comment]
по крайней мере с чатов

**Comment by docpillman** [comment]
)

**Comment by lKanifoll** [comment]
мде)))

**Comment by docpillman** [comment]
)

**Comment by lKanifoll** [comment]
Необходимо повернуть все кварцы кроме часового на 90 градусов

**Comment by docpillman** [comment]
Это ошибка при монтаже или ошибка footprint ?

**Comment by lKanifoll** [comment]
Ошибка footprint
